#!/bin/bash

CURRENT_PATH=$PWD

SCRIPT_PATH="`dirname \"$0\"`"
SCRIPT_PATH="`( cd \"$SCRIPT_PATH\" && pwd )`"  # absolutized and normalized
if [ -z "$SCRIPT_PATH" ] ; then
  # error; for some reason, the path is not accessible
  # to the script (e.g. permissions re-evaled after suid)
  exit 1  # fail
fi

cd $SCRIPT_PATH

if ! [ -d "node_modules" ];
then
  npm install
fi

gulp "$@" --gulpfile yodafile.js


cd $CURRENT_PATH
